# Generated by Django 4.2.13 on 2024-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userlike_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='is_already_liked',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
