# Generated by Django 4.2.13 on 2024-11-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_personalitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personality_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.personalitytype'),
        ),
    ]
